### ISSUE TITLE
A error after 'kidash --help'

### ISSUE THREAD

**Issue by yodayuuki55** [chaoss/grimoirelab-kidash#48]
I successfully installed kidash but when i use `kidash --help`,i got a error:

> Traceback (most recent call last):
  File "/usr/local/bin/kidash", line 4, in <module>
    __import__('pkg_resources').run_script('kidash==0.4.21', 'kidash')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/kidash' not found in metadata at '/usr/local/lib/python3.6/dist-packages/kidash-0.4.21.dist-info'

how to solve it?

**Comment by yodayuuki55** [comment]
OK, i have solved it.But i got a new error when importing dashboard
`kidash -g -e https://admin:admin@localhost:9200 --import grimoirelab-kidash/onion_organizations.json`

the error:
> 2021-08-23 10:23:57,186 Retrying (Retry(total=20, connect=21, read=8, redirect=5, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)'),)': /.kibana
2021-08-23 10:23:57,588 Retrying (Retry(total=19, connect=21, read=8, redirect=5, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)'),)': /.kibana
2021-08-23 10:23:58,391 Retrying (Retry(total=18, connect=21, read=8, redirect=5, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)'),)': /.kibana
2021-08-23 10:23:59,994 Retrying (Retry(total=17, connect=21, read=8, redirect=5, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)'),)': /.kibana
2021-08-23 10:24:03,200 Retrying (Retry(total=16, connect=21, read=8, redirect=5, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)'),)': /.kibana

**Comment by zhquan** [comment]
Hi @yodayuuki55 

Check if you can access kibana and try again.

`curl -XGET https://admin:admin@localhost:9200/_cat/indices`

Could you share your docker-compose.yml?

Best,
Quan.

**Comment by yodayuuki55** [comment]
> Hi @yodayuuki55
> 
> Check if you can access kibana and try again.
> 
> `curl -XGET https://admin:admin@localhost:9200/_cat/indices`
> 
> Could you share your docker-compose.yml?
> 
> Best,
> Quan.

Thanks for reply！
The following is `curl -XGET  https://admin:admin@localhost:9200/_cat/indices`
```
yellow open git-aoc_demo_enriched 9BA1De5EQ8uauDz4TRVtEg 5 1   0  0   1.2kb   1.2kb
yellow open github_demo_raw       DLHMHCCFRYSxCRyxPvT2mQ 5 1   0  0   1.2kb   1.2kb
yellow open git_demo_raw          3IT6wTfKQou3g9sMTGN8YA 5 1   0  0   1.2kb   1.2kb
yellow open github_demo_enriched  MvnWZGKXQ-KdYOAiGJwn6Q 5 1   0  0   1.2kb   1.2kb
yellow open git_demo_enriched     R7a9lizeRxuKkLlt-n7PNA 5 1   0  0   1.2kb   1.2kb
yellow open .grimoirelab-sigils   gHyEdYDURVKjO4tHPuWlaA 5 1  42  3  73.3kb  73.3kb
green  open .kibana_1             pF-I95nzTE-vPgRL78s9dA 1 0 290 43 403.7kb 403.7kb
```

The following is my docker-compose.yml
```
 services:
    mariadb:
      image: mariadb:10.0
      expose:
        - "3306"
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
 hatstall:
      image: grimoirelab/hatstall:latest
      environment:
        - DATABASE_DIR=/db/
        - ADMIN_USER=admin
        - ADMIN_PASS=admin
      ports:
        - 8000:80
      links:
        - mariadb
      volumes:
        - ../default-grimoirelab-settings/apache-hatstall.conf:/home/grimoirelab/apache-hatstall.conf
        - ../default-grimoirelab-settings/shdb.cfg:/home/grimoirelab/shdb.cfg

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6
      command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
      ports:
        - 9200:9200
      environment:
        - ES_JAVA_OPTS=-Xms2g -Xmx2g
        - ANONYMOUS_USER=true

    kibiter:
      restart: on-failure:5
      image: bitergia/kibiter:community-v6.8.6-3
      environment:
        - PROJECT_NAME=Demo
        - NODE_OPTIONS=--max-old-space-size=1000
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      links:
         - elasticsearch
      ports:
        - 5601:5601

    mordred:
      restart: on-failure:5
      image: bitergia/mordred:latest
      volumes:
        - ../default-grimoirelab-settings/setup.cfg:/home/bitergia/conf/setup.cfg
        - ../default-grimoirelab-settings/aliases.json:/home/bitergia/conf/aliases.json
        - ../default-grimoirelab-settings/projects.json:/home/bitergia/conf/projects.json
        - ../default-grimoirelab-settings/organizations.json:/home/bitergia/conf/organizations.json
        - ../default-grimoirelab-settings/identities.yml:/home/bitergia/conf/identities.yml
        - /tmp/:/home/bitergia/logs
        - /home/NAME/mordred-log:/home/bitergia/logs
      depends_on:
        - mariadb
        - elasticsearch
      mem_limit: 4g
```
